validation: sovereign
version: 1
accounts:
- name: admin
  coins:
  - 100000000000000uekc # 100M EKC
  address: enreach1mwyh5y3nu300s2v2spr3mw8ypf65nzzdmf3lex
- name: validator
  coins:
  - 1000000000000uekc # 1M EKC
  mnemonic: favorite useful have until tattoo buyer else canoe fiber ride rival pear miss scissors almost pill leisure melody mask vacant license target shuffle mass
client:
  typescript:
    path: ts-client
  openapi:
    path: docs/static/openapi.yml
validators:
- name: validator
  bonded: 10000000000uekc # 10000 EKC
  app:
    minimum-gas-prices: "0.01uekc"
    pruning: "nothing"
  config:
    moniker: "EnreachKeeperNode"
    proxy_app: "tcp://0.0.0.0:26658"
    rpc:
      laddr: "tcp://0.0.0.0:26657"
    p2p:
      laddr: "tcp://0.0.0.0:26656"
    consensus:
      timeout_propose: "2s"
      timeout_commit: "3s"
      create_empty_blocks_interval: "3s"
  client:
    chain-id: "enreach"
genesis:
  app_state:
    bank:
      denom_metadata:
      - description: $EKC is the native token of the Enreach Keeper Chain.
        denom_units:
          - denom: "uekc"
            exponent: 0
            aliases: ["microekc"]
          - denom: "ekc"
            exponent: 6
        base: "uekc"
        display: "ekc"
        name: "EK Coin"
        symbol: "EKC"
    mint:
      params:
        mint_denom: "uekc" 
        inflation_max: "0"  # Disable auto inflation
        inflation_min: "0"
    staking:
      params:
        bond_denom: "uekc"
    gov:
      params:
        min_deposit: 
          - denom: "uekc"
            amount: "10000000"  # 10 EKC
        expedited_min_deposit:
          - denom: "uekc"
            amount: "50000000"  # 50 EKC
    crisis:
      constant_fee:
        denom: "uekc"
        amount: "10000000"  # 10 EKC
    registry:
      adminAccount: "enreach1mwyh5y3nu300s2v2spr3mw8ypf65nzzdmf3lex"
    manager:
      adminAccount: "enreach1mwyh5y3nu300s2v2spr3mw8ypf65nzzdmf3lex"
    edgenode:
      adminAccount: "enreach1mwyh5y3nu300s2v2spr3mw8ypf65nzzdmf3lex"
    workload:
      adminAccount: "enreach1mwyh5y3nu300s2v2spr3mw8ypf65nzzdmf3lex"
      params:
        data:
          EpochLength: "30"
          EraLength: "120"