validation: sovereign
version: 1
accounts:
- name: admin
  coins:
  - 100000000000000uekc # 100M EKC
  mnemonic: autumn churn regular flee grid category remember put dish uniform age pepper armor portion wait tribe memory inform fine photo work problem blast enforce
- name: superior
  coins:
  - 1000000000000uekc # 1M EKC
  mnemonic: fitness marine video shine dose garlic senior throw room metal seek address stable abstract salmon traffic multiply erode category brass maid joy usual round
- name: operatorA
  coins:
  - 1000000000000uekc # 1M EKC
  mnemonic: frame blame asset doctor below parrot cross latin camp cruel trumpet fix income impose dose culture amused health sniff poem risk ask twenty zone
- name: operatorB
  coins:
  - 1000000000000uekc # 1M EKC
  mnemonic: gather dawn ethics hurdle employ business dad divorce question cable spoil kiss ritual adapt punch divorce invest bench game believe couple useful truly step
- name: operatorC
  coins:
  - 1000000000000uekc # 1M EKC
  mnemonic: crisp flame remain custom cool stable host detail uncle immense tennis shoot eight hello illegal message pause property whip elevator lock beef raccoon drink
- name: managerA
  coins:
  - 1000000000000uekc # 1M EKC
  mnemonic: swallow asthma famous gasp wear velvet actor addict option poem vacuum box path creek slender lamp such inform cable interest quit exchange exclude hurt
- name: managerB
  coins:
  - 1000000000000uekc # 1M EKC
  mnemonic: arch coin juice arrest skill wear engine hobby sniff enforce gloom dance wood volume program bridge slot juice typical chat basic better limit easy
- name: managerC
  coins:
  - 1000000000000uekc # 1M EKC
  mnemonic: grant about cake lady sing work just breeze outdoor candy lazy envelope love penalty ready remember note flip assist immune echo pill mouse core
- name: validator
  coins:
  - 1000000000000uekc # 1M EKC
  mnemonic: favorite useful have until tattoo buyer else canoe fiber ride rival pear miss scissors almost pill leisure melody mask vacant license target shuffle mass
faucet:
  name: validator
  coins:
  - 5ekc
client:
  typescript:
    path: ts-client
  openapi:
    path: docs/static/openapi.yml
validators:
- name: validator
  bonded: 10000000000uekc # 10000 EKC
  app:
    pruning: "nothing"
  config:
    moniker: "EnreachKeeperNode"
    consensus:
      timeout_propose: "2s"
      timeout_commit: "3s"
      create_empty_blocks_interval: "3s"
  client:
    chain-id: "enreach"
genesis:
  app_state:
    bank:
      denom_metadata:
      - description: $EKC is the native token of the Enreach Keeper Chain.
        denom_units:
          - denom: "uekc"
            exponent: 0
            aliases: ["microekc"]
          - denom: "ekc"
            exponent: 6
        base: "uekc"
        display: "ekc"
        name: "EK Coin"
        symbol: "EKC"
    mint:
      params:
        mint_denom: "uekc" 
        inflation_max: "0"  # Disable auto inflation
        inflation_min: "0"
    staking:
      params:
        bond_denom: "uekc"
    gov:
      params:
        min_deposit: 
          - denom: "uekc"
            amount: "10000000"  # 10 EKC
        expedited_min_deposit:
          - denom: "uekc"
            amount: "50000000"  # 50 EKC
    crisis:
      constant_fee:
        denom: "uekc"
        amount: "10000000"  # 10 EKC