package types

const (
	EPOCH_LENGTH = 10

	OPERATOR_NAME_MAX_LENGTH = 30
	OPERATOR_DESC_MAX_LENGTH = 256
	OPERATOR_URL_MAX_LENGTH  = 256

	MANAGER_SIGNATURE_LENGTH = 65

	REGION_CODE_MAX_LENGTH = 10

	HOST_ADDRESS_MAX_LENGTH = 128
	PORT_MAX_VALUE          = 65535

	LICENSE_MAX_LENGTH       = 256
	LICENSE_SIGNATURE_LENGTH = 64

	EVM_ACCOUNT_LENGTH   = 42
	EVM_SIGNATURE_LENGTH = 65
)
