swagger: '2.0'
info:
  title: HTTP API Console enreach.edgenode
  name: ''
  description: ''
paths:
  /enreach/edgenode/node/{nodeID}:
    get:
      operationId: Query_Node
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Node:
                type: object
                properties:
                  nodeID:
                    type: string
                  userID:
                    type: string
                  nodeName:
                    type: string
                  deviceType:
                    type: string
                  regionCode:
                    type: string
                  trafficType:
                    type: integer
                    format: int64
                  registerStatus:
                    type: string
                  workingStatus:
                    type: string
                  creator:
                    type: string
                  createAt:
                    type: string
                    format: uint64
                  updator:
                    type: string
                  updateAt:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: nodeID
          in: path
          required: true
          type: string
      tags:
        - Query
  /enreach/edgenode/nodes:
    get:
      operationId: Query_NodeAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Node:
                type: array
                items:
                  type: object
                  properties:
                    nodeID:
                      type: string
                    userID:
                      type: string
                    nodeName:
                      type: string
                    deviceType:
                      type: string
                    regionCode:
                      type: string
                    trafficType:
                      type: integer
                      format: int64
                    registerStatus:
                      type: string
                    workingStatus:
                      type: string
                    creator:
                      type: string
                    createAt:
                      type: string
                      format: uint64
                    updator:
                      type: string
                    updateAt:
                      type: string
                      format: uint64
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /enreach/edgenode/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /enreach/edgenode/superior:
    get:
      operationId: Query_Superior
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Superior:
                type: object
                properties:
                  account:
                    type: string
                  creator:
                    type: string
                  createAt:
                    type: string
                    format: uint64
                  updator:
                    type: string
                  updateAt:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /enreach/edgenode/user/{userID}:
    get:
      operationId: Query_User
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              User:
                type: object
                properties:
                  userID:
                    type: string
                  evmAccount:
                    type: string
                  creator:
                    type: string
                  createAt:
                    type: string
                    format: uint64
                  updator:
                    type: string
                  updateAt:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: userID
          in: path
          required: true
          type: string
      tags:
        - Query
  /enreach/edgenode/users:
    get:
      operationId: Query_UserAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              User:
                type: array
                items:
                  type: object
                  properties:
                    userID:
                      type: string
                    evmAccount:
                      type: string
                    creator:
                      type: string
                    createAt:
                      type: string
                      format: uint64
                    updator:
                      type: string
                    updateAt:
                      type: string
                      format: uint64
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  QueryAllNodeResponse:
    type: object
    properties:
      Node:
        type: array
        items:
          type: object
          properties:
            nodeID:
              type: string
            userID:
              type: string
            nodeName:
              type: string
            deviceType:
              type: string
            regionCode:
              type: string
            trafficType:
              type: integer
              format: int64
            registerStatus:
              type: string
            workingStatus:
              type: string
            creator:
              type: string
            createAt:
              type: string
              format: uint64
            updator:
              type: string
            updateAt:
              type: string
              format: uint64
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryAllUserResponse:
    type: object
    properties:
      User:
        type: array
        items:
          type: object
          properties:
            userID:
              type: string
            evmAccount:
              type: string
            creator:
              type: string
            createAt:
              type: string
              format: uint64
            updator:
              type: string
            updateAt:
              type: string
              format: uint64
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryGetNodeResponse:
    type: object
    properties:
      Node:
        type: object
        properties:
          nodeID:
            type: string
          userID:
            type: string
          nodeName:
            type: string
          deviceType:
            type: string
          regionCode:
            type: string
          trafficType:
            type: integer
            format: int64
          registerStatus:
            type: string
          workingStatus:
            type: string
          creator:
            type: string
          createAt:
            type: string
            format: uint64
          updator:
            type: string
          updateAt:
            type: string
            format: uint64
  QueryGetSuperiorResponse:
    type: object
    properties:
      Superior:
        type: object
        properties:
          account:
            type: string
          creator:
            type: string
          createAt:
            type: string
            format: uint64
          updator:
            type: string
          updateAt:
            type: string
            format: uint64
  QueryGetUserResponse:
    type: object
    properties:
      User:
        type: object
        properties:
          userID:
            type: string
          evmAccount:
            type: string
          creator:
            type: string
          createAt:
            type: string
            format: uint64
          updator:
            type: string
          updateAt:
            type: string
            format: uint64
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  edgenode.Node:
    type: object
    properties:
      nodeID:
        type: string
      userID:
        type: string
      nodeName:
        type: string
      deviceType:
        type: string
      regionCode:
        type: string
      trafficType:
        type: integer
        format: int64
      registerStatus:
        type: string
      workingStatus:
        type: string
      creator:
        type: string
      createAt:
        type: string
        format: uint64
      updator:
        type: string
      updateAt:
        type: string
        format: uint64
  edgenode.Params:
    type: object
  edgenode.Superior:
    type: object
    properties:
      account:
        type: string
      creator:
        type: string
      createAt:
        type: string
        format: uint64
      updator:
        type: string
      updateAt:
        type: string
        format: uint64
  edgenode.User:
    type: object
    properties:
      userID:
        type: string
      evmAccount:
        type: string
      creator:
        type: string
      createAt:
        type: string
        format: uint64
      updator:
        type: string
      updateAt:
        type: string
        format: uint64
  MsgBindAndActivateNodeResponse:
    type: object
  MsgBindUserEVMAccountResponse:
    type: object
  MsgCreateSuperiorResponse:
    type: object
  MsgCreateUserResponse:
    type: object
  MsgRegisterNodeResponse:
    type: object
  MsgUnbindNodeResponse:
    type: object
  MsgUpdateNodeTrafficTypeBatchResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
  MsgUpdateSuperiorResponse:
    type: object
  Params:
    type: object
