swagger: '2.0'
info:
  title: HTTP API Console enreach.manager
  name: ''
  description: ''
paths:
  /enreach/manager/get_manager_by_region/{regionCode}:
    get:
      operationId: Query_GetManagerByRegion
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              managers:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uint64
                    managerAddress:
                      type: string
                    operatorName:
                      type: string
                    operatorDesc:
                      type: string
                    operatorWebsiteURL:
                      type: string
                    evmAddress:
                      type: string
                    hostAddress:
                      type: string
                    managerPort:
                      type: integer
                      format: int64
                    trackerPort:
                      type: integer
                      format: int64
                    chainAPIPort:
                      type: integer
                      format: int64
                    chainRPCPort:
                      type: integer
                      format: int64
                    regionCode:
                      type: string
                    status:
                      type: string
                    creator:
                      type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: regionCode
          in: path
          required: true
          type: string
      tags:
        - Query
  /enreach/manager/manager/{id}:
    get:
      operationId: Query_Manager
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Manager:
                type: object
                properties:
                  id:
                    type: string
                    format: uint64
                  managerAddress:
                    type: string
                  operatorName:
                    type: string
                  operatorDesc:
                    type: string
                  operatorWebsiteURL:
                    type: string
                  evmAddress:
                    type: string
                  hostAddress:
                    type: string
                  managerPort:
                    type: integer
                    format: int64
                  trackerPort:
                    type: integer
                    format: int64
                  chainAPIPort:
                    type: integer
                    format: int64
                  chainRPCPort:
                    type: integer
                    format: int64
                  regionCode:
                    type: string
                  status:
                    type: string
                  creator:
                    type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uint64
      tags:
        - Query
  /enreach/manager/managers:
    get:
      operationId: Query_ManagerAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Manager:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uint64
                    managerAddress:
                      type: string
                    operatorName:
                      type: string
                    operatorDesc:
                      type: string
                    operatorWebsiteURL:
                      type: string
                    evmAddress:
                      type: string
                    hostAddress:
                      type: string
                    managerPort:
                      type: integer
                      format: int64
                    trackerPort:
                      type: integer
                      format: int64
                    chainAPIPort:
                      type: integer
                      format: int64
                    chainRPCPort:
                      type: integer
                      format: int64
                    regionCode:
                      type: string
                    status:
                      type: string
                    creator:
                      type: string
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /enreach/manager/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  QueryAllManagerResponse:
    type: object
    properties:
      Manager:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uint64
            managerAddress:
              type: string
            operatorName:
              type: string
            operatorDesc:
              type: string
            operatorWebsiteURL:
              type: string
            evmAddress:
              type: string
            hostAddress:
              type: string
            managerPort:
              type: integer
              format: int64
            trackerPort:
              type: integer
              format: int64
            chainAPIPort:
              type: integer
              format: int64
            chainRPCPort:
              type: integer
              format: int64
            regionCode:
              type: string
            status:
              type: string
            creator:
              type: string
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryGetManagerByRegionResponse:
    type: object
    properties:
      managers:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uint64
            managerAddress:
              type: string
            operatorName:
              type: string
            operatorDesc:
              type: string
            operatorWebsiteURL:
              type: string
            evmAddress:
              type: string
            hostAddress:
              type: string
            managerPort:
              type: integer
              format: int64
            trackerPort:
              type: integer
              format: int64
            chainAPIPort:
              type: integer
              format: int64
            chainRPCPort:
              type: integer
              format: int64
            regionCode:
              type: string
            status:
              type: string
            creator:
              type: string
  QueryGetManagerResponse:
    type: object
    properties:
      Manager:
        type: object
        properties:
          id:
            type: string
            format: uint64
          managerAddress:
            type: string
          operatorName:
            type: string
          operatorDesc:
            type: string
          operatorWebsiteURL:
            type: string
          evmAddress:
            type: string
          hostAddress:
            type: string
          managerPort:
            type: integer
            format: int64
          trackerPort:
            type: integer
            format: int64
          chainAPIPort:
            type: integer
            format: int64
          chainRPCPort:
            type: integer
            format: int64
          regionCode:
            type: string
          status:
            type: string
          creator:
            type: string
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  manager.Manager:
    type: object
    properties:
      id:
        type: string
        format: uint64
      managerAddress:
        type: string
      operatorName:
        type: string
      operatorDesc:
        type: string
      operatorWebsiteURL:
        type: string
      evmAddress:
        type: string
      hostAddress:
        type: string
      managerPort:
        type: integer
        format: int64
      trackerPort:
        type: integer
        format: int64
      chainAPIPort:
        type: integer
        format: int64
      chainRPCPort:
        type: integer
        format: int64
      regionCode:
        type: string
      status:
        type: string
      creator:
        type: string
  manager.Params:
    type: object
  MsgDeleteManagerResponse:
    type: object
  MsgRegisterManagerResponse:
    type: object
    properties:
      id:
        type: string
        format: uint64
  MsgUpdateManagerResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
  Params:
    type: object
