swagger: '2.0'
info:
  title: HTTP API Console enreach.workload
  name: ''
  description: ''
paths:
  /enreach/workload/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /enreach/workload/workload/{id}:
    get:
      operationId: Query_Workload
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Workload:
                type: object
                properties:
                  id:
                    type: string
                    format: uint64
                  managerAccount:
                    type: string
                  epoch:
                    type: string
                    format: uint64
                  nodeID:
                    type: string
                  score:
                    type: string
                    format: uint64
                  createAt:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uint64
      tags:
        - Query
  /enreach/workload/workloads:
    get:
      operationId: Query_WorkloadAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Workload:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uint64
                    managerAccount:
                      type: string
                    epoch:
                      type: string
                      format: uint64
                    nodeID:
                      type: string
                    score:
                      type: string
                      format: uint64
                    createAt:
                      type: string
                      format: uint64
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /enreach/workload/workreport/{epoch}/{nodeID}:
    get:
      operationId: Query_GetWorkreport
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Workreport:
                type: object
                properties:
                  epoch:
                    type: string
                    format: uint64
                  nodeID:
                    type: string
                  managerScoreMap:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        score:
                          type: string
                          format: uint64
                        createAt:
                          type: string
                          format: uint64
                        updateAt:
                          type: string
                          format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: epoch
          in: path
          required: true
          type: string
          format: uint64
        - name: nodeID
          in: path
          required: true
          type: string
      tags:
        - Query
  /enreach/workload/workreports/{epoch}:
    get:
      operationId: Query_GetAllWorkreportByEpoch
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Workreport:
                type: array
                items:
                  type: object
                  properties:
                    epoch:
                      type: string
                      format: uint64
                    nodeID:
                      type: string
                    managerScoreMap:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          score:
                            type: string
                            format: uint64
                          createAt:
                            type: string
                            format: uint64
                          updateAt:
                            type: string
                            format: uint64
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: epoch
          in: path
          required: true
          type: string
          format: uint64
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  NodeScoreDB:
    type: object
    properties:
      score:
        type: string
        format: uint64
      createAt:
        type: string
        format: uint64
      updateAt:
        type: string
        format: uint64
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  QueryAllWorkloadResponse:
    type: object
    properties:
      Workload:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uint64
            managerAccount:
              type: string
            epoch:
              type: string
              format: uint64
            nodeID:
              type: string
            score:
              type: string
              format: uint64
            createAt:
              type: string
              format: uint64
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryGetAllWorkreportByEpochResponse:
    type: object
    properties:
      Workreport:
        type: array
        items:
          type: object
          properties:
            epoch:
              type: string
              format: uint64
            nodeID:
              type: string
            managerScoreMap:
              type: object
              additionalProperties:
                type: object
                properties:
                  score:
                    type: string
                    format: uint64
                  createAt:
                    type: string
                    format: uint64
                  updateAt:
                    type: string
                    format: uint64
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryGetWorkloadResponse:
    type: object
    properties:
      Workload:
        type: object
        properties:
          id:
            type: string
            format: uint64
          managerAccount:
            type: string
          epoch:
            type: string
            format: uint64
          nodeID:
            type: string
          score:
            type: string
            format: uint64
          createAt:
            type: string
            format: uint64
  QueryGetWorkreportResponse:
    type: object
    properties:
      Workreport:
        type: object
        properties:
          epoch:
            type: string
            format: uint64
          nodeID:
            type: string
          managerScoreMap:
            type: object
            additionalProperties:
              type: object
              properties:
                score:
                  type: string
                  format: uint64
                createAt:
                  type: string
                  format: uint64
                updateAt:
                  type: string
                  format: uint64
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  Workreport:
    type: object
    properties:
      epoch:
        type: string
        format: uint64
      nodeID:
        type: string
      managerScoreMap:
        type: object
        additionalProperties:
          type: object
          properties:
            score:
              type: string
              format: uint64
            createAt:
              type: string
              format: uint64
            updateAt:
              type: string
              format: uint64
  workload.Params:
    type: object
  workload.Workload:
    type: object
    properties:
      id:
        type: string
        format: uint64
      managerAccount:
        type: string
      epoch:
        type: string
        format: uint64
      nodeID:
        type: string
      score:
        type: string
        format: uint64
      createAt:
        type: string
        format: uint64
  MsgSubmitWorkreportsResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
  NodeScore:
    type: object
    properties:
      nodeID:
        type: string
      score:
        type: string
        format: uint64
  Params:
    type: object
