// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: enreach/workload/query.proto

package workload

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName                            = "/enreach.workload.Query/Params"
	Query_EpochLength_FullMethodName                       = "/enreach.workload.Query/EpochLength"
	Query_CurrentEpoch_FullMethodName                      = "/enreach.workload.Query/CurrentEpoch"
	Query_PendingNextEpoch_FullMethodName                  = "/enreach.workload.Query/PendingNextEpoch"
	Query_HistoryEpoch_FullMethodName                      = "/enreach.workload.Query/HistoryEpoch"
	Query_AllHistoryEpoch_FullMethodName                   = "/enreach.workload.Query/AllHistoryEpoch"
	Query_NodeWorkload_FullMethodName                      = "/enreach.workload.Query/NodeWorkload"
	Query_AllNodeWorkloadByEpoch_FullMethodName            = "/enreach.workload.Query/AllNodeWorkloadByEpoch"
	Query_ManagerWRWorkload_FullMethodName                 = "/enreach.workload.Query/ManagerWRWorkload"
	Query_AllManagerWRWorkloadByEpoch_FullMethodName       = "/enreach.workload.Query/AllManagerWRWorkloadByEpoch"
	Query_ManagerRPWorkload_FullMethodName                 = "/enreach.workload.Query/ManagerRPWorkload"
	Query_AllManagerRPWorkloadByEra_FullMethodName         = "/enreach.workload.Query/AllManagerRPWorkloadByEra"
	Query_ManagerCSWorkload_FullMethodName                 = "/enreach.workload.Query/ManagerCSWorkload"
	Query_AllManagerCSWorkloadByEra_FullMethodName         = "/enreach.workload.Query/AllManagerCSWorkloadByEra"
	Query_Workreport_FullMethodName                        = "/enreach.workload.Query/Workreport"
	Query_AllWorkreportByEpoch_FullMethodName              = "/enreach.workload.Query/AllWorkreportByEpoch"
	Query_WorkreportProcessBatchSize_FullMethodName        = "/enreach.workload.Query/WorkreportProcessBatchSize"
	Query_HistoryEpochDataDepth_FullMethodName             = "/enreach.workload.Query/HistoryEpochDataDepth"
	Query_EpochProcessData_FullMethodName                  = "/enreach.workload.Query/EpochProcessData"
	Query_AllEpochProcessData_FullMethodName               = "/enreach.workload.Query/AllEpochProcessData"
	Query_Superior_FullMethodName                          = "/enreach.workload.Query/Superior"
	Query_EraLength_FullMethodName                         = "/enreach.workload.Query/EraLength"
	Query_CurrentEra_FullMethodName                        = "/enreach.workload.Query/CurrentEra"
	Query_PendingNextEra_FullMethodName                    = "/enreach.workload.Query/PendingNextEra"
	Query_HistoryEra_FullMethodName                        = "/enreach.workload.Query/HistoryEra"
	Query_AllHistoryEra_FullMethodName                     = "/enreach.workload.Query/AllHistoryEra"
	Query_ReputationPointChangeData_FullMethodName         = "/enreach.workload.Query/ReputationPointChangeData"
	Query_AllReputationPointChangeDataByEra_FullMethodName = "/enreach.workload.Query/AllReputationPointChangeDataByEra"
	Query_ReputationDeltaPoint_FullMethodName              = "/enreach.workload.Query/ReputationDeltaPoint"
	Query_AllReputationDeltaPointByEra_FullMethodName      = "/enreach.workload.Query/AllReputationDeltaPointByEra"
	Query_EraProcessData_FullMethodName                    = "/enreach.workload.Query/EraProcessData"
	Query_AllEraProcessData_FullMethodName                 = "/enreach.workload.Query/AllEraProcessData"
	Query_CheatStatusCRData_FullMethodName                 = "/enreach.workload.Query/CheatStatusCRData"
	Query_AllCheatStatusCRDataByEra_FullMethodName         = "/enreach.workload.Query/AllCheatStatusCRDataByEra"
	Query_EraCheatStatusProcessData_FullMethodName         = "/enreach.workload.Query/EraCheatStatusProcessData"
	Query_AllEraCheatStatusProcessData_FullMethodName      = "/enreach.workload.Query/AllEraCheatStatusProcessData"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries epoch
	EpochLength(ctx context.Context, in *QueryGetEpochLengthRequest, opts ...grpc.CallOption) (*QueryGetEpochLengthResponse, error)
	CurrentEpoch(ctx context.Context, in *QueryGetCurrentEpochRequest, opts ...grpc.CallOption) (*QueryGetCurrentEpochResponse, error)
	PendingNextEpoch(ctx context.Context, in *QueryGetPendingNextEpochRequest, opts ...grpc.CallOption) (*QueryGetPendingNextEpochResponse, error)
	HistoryEpoch(ctx context.Context, in *QueryGetHistoryEpochRequest, opts ...grpc.CallOption) (*QueryGetHistoryEpochResponse, error)
	AllHistoryEpoch(ctx context.Context, in *QueryGetAllHistoryEpochRequest, opts ...grpc.CallOption) (*QueryGetAllHistoryEpochResponse, error)
	// Queries a list of Node Workload items.
	NodeWorkload(ctx context.Context, in *QueryGetNodeWorkloadRequest, opts ...grpc.CallOption) (*QueryGetNodeWorkloadResponse, error)
	AllNodeWorkloadByEpoch(ctx context.Context, in *QueryGetAllNodeWorkloadByEpochRequest, opts ...grpc.CallOption) (*QueryGetAllNodeWorkloadByEpochResponse, error)
	// Queries a list of Manager Workload items.
	ManagerWRWorkload(ctx context.Context, in *QueryGetManagerWRWorkloadRequest, opts ...grpc.CallOption) (*QueryGetManagerWRWorkloadResponse, error)
	AllManagerWRWorkloadByEpoch(ctx context.Context, in *QueryGetAllManagerWRWorkloadByEpochRequest, opts ...grpc.CallOption) (*QueryGetAllManagerWRWorkloadByEpochResponse, error)
	ManagerRPWorkload(ctx context.Context, in *QueryGetManagerRPWorkloadRequest, opts ...grpc.CallOption) (*QueryGetManagerRPWorkloadResponse, error)
	AllManagerRPWorkloadByEra(ctx context.Context, in *QueryGetAllManagerRPWorkloadByEraRequest, opts ...grpc.CallOption) (*QueryGetAllManagerRPWorkloadByEraResponse, error)
	ManagerCSWorkload(ctx context.Context, in *QueryGetManagerCSWorkloadRequest, opts ...grpc.CallOption) (*QueryGetManagerCSWorkloadResponse, error)
	AllManagerCSWorkloadByEra(ctx context.Context, in *QueryGetAllManagerCSWorkloadByEraRequest, opts ...grpc.CallOption) (*QueryGetAllManagerCSWorkloadByEraResponse, error)
	// Queries a list of Workreport items.
	Workreport(ctx context.Context, in *QueryGetWorkreportRequest, opts ...grpc.CallOption) (*QueryGetWorkreportResponse, error)
	AllWorkreportByEpoch(ctx context.Context, in *QueryGetAllWorkreportByEpochRequest, opts ...grpc.CallOption) (*QueryGetAllWorkreportByEpochResponse, error)
	// Queries some param settings
	WorkreportProcessBatchSize(ctx context.Context, in *QueryGetWorkreportProcessBatchSizeRequest, opts ...grpc.CallOption) (*QueryGetWorkreportProcessBatchSizeResponse, error)
	HistoryEpochDataDepth(ctx context.Context, in *QueryGetHistoryEpochDataDepthRequest, opts ...grpc.CallOption) (*QueryGetHistoryEpochDataDepthResponse, error)
	EpochProcessData(ctx context.Context, in *QueryGetEpochProcessDataRequest, opts ...grpc.CallOption) (*QueryGetEpochProcessDataResponse, error)
	AllEpochProcessData(ctx context.Context, in *QueryGetAllEpochProcessDataRequest, opts ...grpc.CallOption) (*QueryGetAllEpochProcessDataResponse, error)
	// Queries a Superior
	Superior(ctx context.Context, in *QueryGetSuperiorRequest, opts ...grpc.CallOption) (*QueryGetSuperiorResponse, error)
	// Queries era
	EraLength(ctx context.Context, in *QueryGetEraLengthRequest, opts ...grpc.CallOption) (*QueryGetEraLengthResponse, error)
	CurrentEra(ctx context.Context, in *QueryGetCurrentEraRequest, opts ...grpc.CallOption) (*QueryGetCurrentEraResponse, error)
	PendingNextEra(ctx context.Context, in *QueryGetPendingNextEraRequest, opts ...grpc.CallOption) (*QueryGetPendingNextEraResponse, error)
	HistoryEra(ctx context.Context, in *QueryGetHistoryEraRequest, opts ...grpc.CallOption) (*QueryGetHistoryEraResponse, error)
	AllHistoryEra(ctx context.Context, in *QueryGetAllHistoryEraRequest, opts ...grpc.CallOption) (*QueryGetAllHistoryEraResponse, error)
	// Queries a list of ReputationPointChangeData items.
	ReputationPointChangeData(ctx context.Context, in *QueryGetReputationPointChangeDataRequest, opts ...grpc.CallOption) (*QueryGetReputationPointChangeDataResponse, error)
	AllReputationPointChangeDataByEra(ctx context.Context, in *QueryGetAllReputationPointChangeDataByEraRequest, opts ...grpc.CallOption) (*QueryGetAllReputationPointChangeDataByEraResponse, error)
	// Queries a list of ReputationPoint items.
	ReputationDeltaPoint(ctx context.Context, in *QueryGetReputationDeltaPointRequest, opts ...grpc.CallOption) (*QueryGetReputationDeltaPointResponse, error)
	AllReputationDeltaPointByEra(ctx context.Context, in *QueryGetAllReputationDeltaPointByEraRequest, opts ...grpc.CallOption) (*QueryGetAllReputationDeltaPointByEraResponse, error)
	// Queries a list of EraProcessData items.
	EraProcessData(ctx context.Context, in *QueryGetEraProcessDataRequest, opts ...grpc.CallOption) (*QueryGetEraProcessDataResponse, error)
	AllEraProcessData(ctx context.Context, in *QueryGetAllEraProcessDataRequest, opts ...grpc.CallOption) (*QueryGetAllEraProcessDataResponse, error)
	// Queries a list of CheatStatusPRData items.
	CheatStatusCRData(ctx context.Context, in *QueryGetCheatStatusCRDataRequest, opts ...grpc.CallOption) (*QueryGetCheatStatusCRDataResponse, error)
	AllCheatStatusCRDataByEra(ctx context.Context, in *QueryGetAllCheatStatusCRDataByEraRequest, opts ...grpc.CallOption) (*QueryGetAllCheatStatusCRDataByEraResponse, error)
	// Queries a list of EraCheatStatusProcessData items.
	EraCheatStatusProcessData(ctx context.Context, in *QueryGetEraCheatStatusProcessDataRequest, opts ...grpc.CallOption) (*QueryGetEraCheatStatusProcessDataResponse, error)
	AllEraCheatStatusProcessData(ctx context.Context, in *QueryGetAllEraCheatStatusProcessDataRequest, opts ...grpc.CallOption) (*QueryGetAllEraCheatStatusProcessDataResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EpochLength(ctx context.Context, in *QueryGetEpochLengthRequest, opts ...grpc.CallOption) (*QueryGetEpochLengthResponse, error) {
	out := new(QueryGetEpochLengthResponse)
	err := c.cc.Invoke(ctx, Query_EpochLength_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CurrentEpoch(ctx context.Context, in *QueryGetCurrentEpochRequest, opts ...grpc.CallOption) (*QueryGetCurrentEpochResponse, error) {
	out := new(QueryGetCurrentEpochResponse)
	err := c.cc.Invoke(ctx, Query_CurrentEpoch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingNextEpoch(ctx context.Context, in *QueryGetPendingNextEpochRequest, opts ...grpc.CallOption) (*QueryGetPendingNextEpochResponse, error) {
	out := new(QueryGetPendingNextEpochResponse)
	err := c.cc.Invoke(ctx, Query_PendingNextEpoch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) HistoryEpoch(ctx context.Context, in *QueryGetHistoryEpochRequest, opts ...grpc.CallOption) (*QueryGetHistoryEpochResponse, error) {
	out := new(QueryGetHistoryEpochResponse)
	err := c.cc.Invoke(ctx, Query_HistoryEpoch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllHistoryEpoch(ctx context.Context, in *QueryGetAllHistoryEpochRequest, opts ...grpc.CallOption) (*QueryGetAllHistoryEpochResponse, error) {
	out := new(QueryGetAllHistoryEpochResponse)
	err := c.cc.Invoke(ctx, Query_AllHistoryEpoch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NodeWorkload(ctx context.Context, in *QueryGetNodeWorkloadRequest, opts ...grpc.CallOption) (*QueryGetNodeWorkloadResponse, error) {
	out := new(QueryGetNodeWorkloadResponse)
	err := c.cc.Invoke(ctx, Query_NodeWorkload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllNodeWorkloadByEpoch(ctx context.Context, in *QueryGetAllNodeWorkloadByEpochRequest, opts ...grpc.CallOption) (*QueryGetAllNodeWorkloadByEpochResponse, error) {
	out := new(QueryGetAllNodeWorkloadByEpochResponse)
	err := c.cc.Invoke(ctx, Query_AllNodeWorkloadByEpoch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ManagerWRWorkload(ctx context.Context, in *QueryGetManagerWRWorkloadRequest, opts ...grpc.CallOption) (*QueryGetManagerWRWorkloadResponse, error) {
	out := new(QueryGetManagerWRWorkloadResponse)
	err := c.cc.Invoke(ctx, Query_ManagerWRWorkload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllManagerWRWorkloadByEpoch(ctx context.Context, in *QueryGetAllManagerWRWorkloadByEpochRequest, opts ...grpc.CallOption) (*QueryGetAllManagerWRWorkloadByEpochResponse, error) {
	out := new(QueryGetAllManagerWRWorkloadByEpochResponse)
	err := c.cc.Invoke(ctx, Query_AllManagerWRWorkloadByEpoch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ManagerRPWorkload(ctx context.Context, in *QueryGetManagerRPWorkloadRequest, opts ...grpc.CallOption) (*QueryGetManagerRPWorkloadResponse, error) {
	out := new(QueryGetManagerRPWorkloadResponse)
	err := c.cc.Invoke(ctx, Query_ManagerRPWorkload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllManagerRPWorkloadByEra(ctx context.Context, in *QueryGetAllManagerRPWorkloadByEraRequest, opts ...grpc.CallOption) (*QueryGetAllManagerRPWorkloadByEraResponse, error) {
	out := new(QueryGetAllManagerRPWorkloadByEraResponse)
	err := c.cc.Invoke(ctx, Query_AllManagerRPWorkloadByEra_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ManagerCSWorkload(ctx context.Context, in *QueryGetManagerCSWorkloadRequest, opts ...grpc.CallOption) (*QueryGetManagerCSWorkloadResponse, error) {
	out := new(QueryGetManagerCSWorkloadResponse)
	err := c.cc.Invoke(ctx, Query_ManagerCSWorkload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllManagerCSWorkloadByEra(ctx context.Context, in *QueryGetAllManagerCSWorkloadByEraRequest, opts ...grpc.CallOption) (*QueryGetAllManagerCSWorkloadByEraResponse, error) {
	out := new(QueryGetAllManagerCSWorkloadByEraResponse)
	err := c.cc.Invoke(ctx, Query_AllManagerCSWorkloadByEra_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Workreport(ctx context.Context, in *QueryGetWorkreportRequest, opts ...grpc.CallOption) (*QueryGetWorkreportResponse, error) {
	out := new(QueryGetWorkreportResponse)
	err := c.cc.Invoke(ctx, Query_Workreport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllWorkreportByEpoch(ctx context.Context, in *QueryGetAllWorkreportByEpochRequest, opts ...grpc.CallOption) (*QueryGetAllWorkreportByEpochResponse, error) {
	out := new(QueryGetAllWorkreportByEpochResponse)
	err := c.cc.Invoke(ctx, Query_AllWorkreportByEpoch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) WorkreportProcessBatchSize(ctx context.Context, in *QueryGetWorkreportProcessBatchSizeRequest, opts ...grpc.CallOption) (*QueryGetWorkreportProcessBatchSizeResponse, error) {
	out := new(QueryGetWorkreportProcessBatchSizeResponse)
	err := c.cc.Invoke(ctx, Query_WorkreportProcessBatchSize_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) HistoryEpochDataDepth(ctx context.Context, in *QueryGetHistoryEpochDataDepthRequest, opts ...grpc.CallOption) (*QueryGetHistoryEpochDataDepthResponse, error) {
	out := new(QueryGetHistoryEpochDataDepthResponse)
	err := c.cc.Invoke(ctx, Query_HistoryEpochDataDepth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EpochProcessData(ctx context.Context, in *QueryGetEpochProcessDataRequest, opts ...grpc.CallOption) (*QueryGetEpochProcessDataResponse, error) {
	out := new(QueryGetEpochProcessDataResponse)
	err := c.cc.Invoke(ctx, Query_EpochProcessData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllEpochProcessData(ctx context.Context, in *QueryGetAllEpochProcessDataRequest, opts ...grpc.CallOption) (*QueryGetAllEpochProcessDataResponse, error) {
	out := new(QueryGetAllEpochProcessDataResponse)
	err := c.cc.Invoke(ctx, Query_AllEpochProcessData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Superior(ctx context.Context, in *QueryGetSuperiorRequest, opts ...grpc.CallOption) (*QueryGetSuperiorResponse, error) {
	out := new(QueryGetSuperiorResponse)
	err := c.cc.Invoke(ctx, Query_Superior_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EraLength(ctx context.Context, in *QueryGetEraLengthRequest, opts ...grpc.CallOption) (*QueryGetEraLengthResponse, error) {
	out := new(QueryGetEraLengthResponse)
	err := c.cc.Invoke(ctx, Query_EraLength_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CurrentEra(ctx context.Context, in *QueryGetCurrentEraRequest, opts ...grpc.CallOption) (*QueryGetCurrentEraResponse, error) {
	out := new(QueryGetCurrentEraResponse)
	err := c.cc.Invoke(ctx, Query_CurrentEra_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingNextEra(ctx context.Context, in *QueryGetPendingNextEraRequest, opts ...grpc.CallOption) (*QueryGetPendingNextEraResponse, error) {
	out := new(QueryGetPendingNextEraResponse)
	err := c.cc.Invoke(ctx, Query_PendingNextEra_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) HistoryEra(ctx context.Context, in *QueryGetHistoryEraRequest, opts ...grpc.CallOption) (*QueryGetHistoryEraResponse, error) {
	out := new(QueryGetHistoryEraResponse)
	err := c.cc.Invoke(ctx, Query_HistoryEra_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllHistoryEra(ctx context.Context, in *QueryGetAllHistoryEraRequest, opts ...grpc.CallOption) (*QueryGetAllHistoryEraResponse, error) {
	out := new(QueryGetAllHistoryEraResponse)
	err := c.cc.Invoke(ctx, Query_AllHistoryEra_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReputationPointChangeData(ctx context.Context, in *QueryGetReputationPointChangeDataRequest, opts ...grpc.CallOption) (*QueryGetReputationPointChangeDataResponse, error) {
	out := new(QueryGetReputationPointChangeDataResponse)
	err := c.cc.Invoke(ctx, Query_ReputationPointChangeData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllReputationPointChangeDataByEra(ctx context.Context, in *QueryGetAllReputationPointChangeDataByEraRequest, opts ...grpc.CallOption) (*QueryGetAllReputationPointChangeDataByEraResponse, error) {
	out := new(QueryGetAllReputationPointChangeDataByEraResponse)
	err := c.cc.Invoke(ctx, Query_AllReputationPointChangeDataByEra_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReputationDeltaPoint(ctx context.Context, in *QueryGetReputationDeltaPointRequest, opts ...grpc.CallOption) (*QueryGetReputationDeltaPointResponse, error) {
	out := new(QueryGetReputationDeltaPointResponse)
	err := c.cc.Invoke(ctx, Query_ReputationDeltaPoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllReputationDeltaPointByEra(ctx context.Context, in *QueryGetAllReputationDeltaPointByEraRequest, opts ...grpc.CallOption) (*QueryGetAllReputationDeltaPointByEraResponse, error) {
	out := new(QueryGetAllReputationDeltaPointByEraResponse)
	err := c.cc.Invoke(ctx, Query_AllReputationDeltaPointByEra_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EraProcessData(ctx context.Context, in *QueryGetEraProcessDataRequest, opts ...grpc.CallOption) (*QueryGetEraProcessDataResponse, error) {
	out := new(QueryGetEraProcessDataResponse)
	err := c.cc.Invoke(ctx, Query_EraProcessData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllEraProcessData(ctx context.Context, in *QueryGetAllEraProcessDataRequest, opts ...grpc.CallOption) (*QueryGetAllEraProcessDataResponse, error) {
	out := new(QueryGetAllEraProcessDataResponse)
	err := c.cc.Invoke(ctx, Query_AllEraProcessData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CheatStatusCRData(ctx context.Context, in *QueryGetCheatStatusCRDataRequest, opts ...grpc.CallOption) (*QueryGetCheatStatusCRDataResponse, error) {
	out := new(QueryGetCheatStatusCRDataResponse)
	err := c.cc.Invoke(ctx, Query_CheatStatusCRData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllCheatStatusCRDataByEra(ctx context.Context, in *QueryGetAllCheatStatusCRDataByEraRequest, opts ...grpc.CallOption) (*QueryGetAllCheatStatusCRDataByEraResponse, error) {
	out := new(QueryGetAllCheatStatusCRDataByEraResponse)
	err := c.cc.Invoke(ctx, Query_AllCheatStatusCRDataByEra_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EraCheatStatusProcessData(ctx context.Context, in *QueryGetEraCheatStatusProcessDataRequest, opts ...grpc.CallOption) (*QueryGetEraCheatStatusProcessDataResponse, error) {
	out := new(QueryGetEraCheatStatusProcessDataResponse)
	err := c.cc.Invoke(ctx, Query_EraCheatStatusProcessData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllEraCheatStatusProcessData(ctx context.Context, in *QueryGetAllEraCheatStatusProcessDataRequest, opts ...grpc.CallOption) (*QueryGetAllEraCheatStatusProcessDataResponse, error) {
	out := new(QueryGetAllEraCheatStatusProcessDataResponse)
	err := c.cc.Invoke(ctx, Query_AllEraCheatStatusProcessData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries epoch
	EpochLength(context.Context, *QueryGetEpochLengthRequest) (*QueryGetEpochLengthResponse, error)
	CurrentEpoch(context.Context, *QueryGetCurrentEpochRequest) (*QueryGetCurrentEpochResponse, error)
	PendingNextEpoch(context.Context, *QueryGetPendingNextEpochRequest) (*QueryGetPendingNextEpochResponse, error)
	HistoryEpoch(context.Context, *QueryGetHistoryEpochRequest) (*QueryGetHistoryEpochResponse, error)
	AllHistoryEpoch(context.Context, *QueryGetAllHistoryEpochRequest) (*QueryGetAllHistoryEpochResponse, error)
	// Queries a list of Node Workload items.
	NodeWorkload(context.Context, *QueryGetNodeWorkloadRequest) (*QueryGetNodeWorkloadResponse, error)
	AllNodeWorkloadByEpoch(context.Context, *QueryGetAllNodeWorkloadByEpochRequest) (*QueryGetAllNodeWorkloadByEpochResponse, error)
	// Queries a list of Manager Workload items.
	ManagerWRWorkload(context.Context, *QueryGetManagerWRWorkloadRequest) (*QueryGetManagerWRWorkloadResponse, error)
	AllManagerWRWorkloadByEpoch(context.Context, *QueryGetAllManagerWRWorkloadByEpochRequest) (*QueryGetAllManagerWRWorkloadByEpochResponse, error)
	ManagerRPWorkload(context.Context, *QueryGetManagerRPWorkloadRequest) (*QueryGetManagerRPWorkloadResponse, error)
	AllManagerRPWorkloadByEra(context.Context, *QueryGetAllManagerRPWorkloadByEraRequest) (*QueryGetAllManagerRPWorkloadByEraResponse, error)
	ManagerCSWorkload(context.Context, *QueryGetManagerCSWorkloadRequest) (*QueryGetManagerCSWorkloadResponse, error)
	AllManagerCSWorkloadByEra(context.Context, *QueryGetAllManagerCSWorkloadByEraRequest) (*QueryGetAllManagerCSWorkloadByEraResponse, error)
	// Queries a list of Workreport items.
	Workreport(context.Context, *QueryGetWorkreportRequest) (*QueryGetWorkreportResponse, error)
	AllWorkreportByEpoch(context.Context, *QueryGetAllWorkreportByEpochRequest) (*QueryGetAllWorkreportByEpochResponse, error)
	// Queries some param settings
	WorkreportProcessBatchSize(context.Context, *QueryGetWorkreportProcessBatchSizeRequest) (*QueryGetWorkreportProcessBatchSizeResponse, error)
	HistoryEpochDataDepth(context.Context, *QueryGetHistoryEpochDataDepthRequest) (*QueryGetHistoryEpochDataDepthResponse, error)
	EpochProcessData(context.Context, *QueryGetEpochProcessDataRequest) (*QueryGetEpochProcessDataResponse, error)
	AllEpochProcessData(context.Context, *QueryGetAllEpochProcessDataRequest) (*QueryGetAllEpochProcessDataResponse, error)
	// Queries a Superior
	Superior(context.Context, *QueryGetSuperiorRequest) (*QueryGetSuperiorResponse, error)
	// Queries era
	EraLength(context.Context, *QueryGetEraLengthRequest) (*QueryGetEraLengthResponse, error)
	CurrentEra(context.Context, *QueryGetCurrentEraRequest) (*QueryGetCurrentEraResponse, error)
	PendingNextEra(context.Context, *QueryGetPendingNextEraRequest) (*QueryGetPendingNextEraResponse, error)
	HistoryEra(context.Context, *QueryGetHistoryEraRequest) (*QueryGetHistoryEraResponse, error)
	AllHistoryEra(context.Context, *QueryGetAllHistoryEraRequest) (*QueryGetAllHistoryEraResponse, error)
	// Queries a list of ReputationPointChangeData items.
	ReputationPointChangeData(context.Context, *QueryGetReputationPointChangeDataRequest) (*QueryGetReputationPointChangeDataResponse, error)
	AllReputationPointChangeDataByEra(context.Context, *QueryGetAllReputationPointChangeDataByEraRequest) (*QueryGetAllReputationPointChangeDataByEraResponse, error)
	// Queries a list of ReputationPoint items.
	ReputationDeltaPoint(context.Context, *QueryGetReputationDeltaPointRequest) (*QueryGetReputationDeltaPointResponse, error)
	AllReputationDeltaPointByEra(context.Context, *QueryGetAllReputationDeltaPointByEraRequest) (*QueryGetAllReputationDeltaPointByEraResponse, error)
	// Queries a list of EraProcessData items.
	EraProcessData(context.Context, *QueryGetEraProcessDataRequest) (*QueryGetEraProcessDataResponse, error)
	AllEraProcessData(context.Context, *QueryGetAllEraProcessDataRequest) (*QueryGetAllEraProcessDataResponse, error)
	// Queries a list of CheatStatusPRData items.
	CheatStatusCRData(context.Context, *QueryGetCheatStatusCRDataRequest) (*QueryGetCheatStatusCRDataResponse, error)
	AllCheatStatusCRDataByEra(context.Context, *QueryGetAllCheatStatusCRDataByEraRequest) (*QueryGetAllCheatStatusCRDataByEraResponse, error)
	// Queries a list of EraCheatStatusProcessData items.
	EraCheatStatusProcessData(context.Context, *QueryGetEraCheatStatusProcessDataRequest) (*QueryGetEraCheatStatusProcessDataResponse, error)
	AllEraCheatStatusProcessData(context.Context, *QueryGetAllEraCheatStatusProcessDataRequest) (*QueryGetAllEraCheatStatusProcessDataResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) EpochLength(context.Context, *QueryGetEpochLengthRequest) (*QueryGetEpochLengthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpochLength not implemented")
}
func (UnimplementedQueryServer) CurrentEpoch(context.Context, *QueryGetCurrentEpochRequest) (*QueryGetCurrentEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentEpoch not implemented")
}
func (UnimplementedQueryServer) PendingNextEpoch(context.Context, *QueryGetPendingNextEpochRequest) (*QueryGetPendingNextEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingNextEpoch not implemented")
}
func (UnimplementedQueryServer) HistoryEpoch(context.Context, *QueryGetHistoryEpochRequest) (*QueryGetHistoryEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoryEpoch not implemented")
}
func (UnimplementedQueryServer) AllHistoryEpoch(context.Context, *QueryGetAllHistoryEpochRequest) (*QueryGetAllHistoryEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllHistoryEpoch not implemented")
}
func (UnimplementedQueryServer) NodeWorkload(context.Context, *QueryGetNodeWorkloadRequest) (*QueryGetNodeWorkloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeWorkload not implemented")
}
func (UnimplementedQueryServer) AllNodeWorkloadByEpoch(context.Context, *QueryGetAllNodeWorkloadByEpochRequest) (*QueryGetAllNodeWorkloadByEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllNodeWorkloadByEpoch not implemented")
}
func (UnimplementedQueryServer) ManagerWRWorkload(context.Context, *QueryGetManagerWRWorkloadRequest) (*QueryGetManagerWRWorkloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManagerWRWorkload not implemented")
}
func (UnimplementedQueryServer) AllManagerWRWorkloadByEpoch(context.Context, *QueryGetAllManagerWRWorkloadByEpochRequest) (*QueryGetAllManagerWRWorkloadByEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllManagerWRWorkloadByEpoch not implemented")
}
func (UnimplementedQueryServer) ManagerRPWorkload(context.Context, *QueryGetManagerRPWorkloadRequest) (*QueryGetManagerRPWorkloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManagerRPWorkload not implemented")
}
func (UnimplementedQueryServer) AllManagerRPWorkloadByEra(context.Context, *QueryGetAllManagerRPWorkloadByEraRequest) (*QueryGetAllManagerRPWorkloadByEraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllManagerRPWorkloadByEra not implemented")
}
func (UnimplementedQueryServer) ManagerCSWorkload(context.Context, *QueryGetManagerCSWorkloadRequest) (*QueryGetManagerCSWorkloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManagerCSWorkload not implemented")
}
func (UnimplementedQueryServer) AllManagerCSWorkloadByEra(context.Context, *QueryGetAllManagerCSWorkloadByEraRequest) (*QueryGetAllManagerCSWorkloadByEraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllManagerCSWorkloadByEra not implemented")
}
func (UnimplementedQueryServer) Workreport(context.Context, *QueryGetWorkreportRequest) (*QueryGetWorkreportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Workreport not implemented")
}
func (UnimplementedQueryServer) AllWorkreportByEpoch(context.Context, *QueryGetAllWorkreportByEpochRequest) (*QueryGetAllWorkreportByEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllWorkreportByEpoch not implemented")
}
func (UnimplementedQueryServer) WorkreportProcessBatchSize(context.Context, *QueryGetWorkreportProcessBatchSizeRequest) (*QueryGetWorkreportProcessBatchSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkreportProcessBatchSize not implemented")
}
func (UnimplementedQueryServer) HistoryEpochDataDepth(context.Context, *QueryGetHistoryEpochDataDepthRequest) (*QueryGetHistoryEpochDataDepthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoryEpochDataDepth not implemented")
}
func (UnimplementedQueryServer) EpochProcessData(context.Context, *QueryGetEpochProcessDataRequest) (*QueryGetEpochProcessDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpochProcessData not implemented")
}
func (UnimplementedQueryServer) AllEpochProcessData(context.Context, *QueryGetAllEpochProcessDataRequest) (*QueryGetAllEpochProcessDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllEpochProcessData not implemented")
}
func (UnimplementedQueryServer) Superior(context.Context, *QueryGetSuperiorRequest) (*QueryGetSuperiorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Superior not implemented")
}
func (UnimplementedQueryServer) EraLength(context.Context, *QueryGetEraLengthRequest) (*QueryGetEraLengthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EraLength not implemented")
}
func (UnimplementedQueryServer) CurrentEra(context.Context, *QueryGetCurrentEraRequest) (*QueryGetCurrentEraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentEra not implemented")
}
func (UnimplementedQueryServer) PendingNextEra(context.Context, *QueryGetPendingNextEraRequest) (*QueryGetPendingNextEraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingNextEra not implemented")
}
func (UnimplementedQueryServer) HistoryEra(context.Context, *QueryGetHistoryEraRequest) (*QueryGetHistoryEraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoryEra not implemented")
}
func (UnimplementedQueryServer) AllHistoryEra(context.Context, *QueryGetAllHistoryEraRequest) (*QueryGetAllHistoryEraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllHistoryEra not implemented")
}
func (UnimplementedQueryServer) ReputationPointChangeData(context.Context, *QueryGetReputationPointChangeDataRequest) (*QueryGetReputationPointChangeDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReputationPointChangeData not implemented")
}
func (UnimplementedQueryServer) AllReputationPointChangeDataByEra(context.Context, *QueryGetAllReputationPointChangeDataByEraRequest) (*QueryGetAllReputationPointChangeDataByEraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllReputationPointChangeDataByEra not implemented")
}
func (UnimplementedQueryServer) ReputationDeltaPoint(context.Context, *QueryGetReputationDeltaPointRequest) (*QueryGetReputationDeltaPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReputationDeltaPoint not implemented")
}
func (UnimplementedQueryServer) AllReputationDeltaPointByEra(context.Context, *QueryGetAllReputationDeltaPointByEraRequest) (*QueryGetAllReputationDeltaPointByEraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllReputationDeltaPointByEra not implemented")
}
func (UnimplementedQueryServer) EraProcessData(context.Context, *QueryGetEraProcessDataRequest) (*QueryGetEraProcessDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EraProcessData not implemented")
}
func (UnimplementedQueryServer) AllEraProcessData(context.Context, *QueryGetAllEraProcessDataRequest) (*QueryGetAllEraProcessDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllEraProcessData not implemented")
}
func (UnimplementedQueryServer) CheatStatusCRData(context.Context, *QueryGetCheatStatusCRDataRequest) (*QueryGetCheatStatusCRDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheatStatusCRData not implemented")
}
func (UnimplementedQueryServer) AllCheatStatusCRDataByEra(context.Context, *QueryGetAllCheatStatusCRDataByEraRequest) (*QueryGetAllCheatStatusCRDataByEraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllCheatStatusCRDataByEra not implemented")
}
func (UnimplementedQueryServer) EraCheatStatusProcessData(context.Context, *QueryGetEraCheatStatusProcessDataRequest) (*QueryGetEraCheatStatusProcessDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EraCheatStatusProcessData not implemented")
}
func (UnimplementedQueryServer) AllEraCheatStatusProcessData(context.Context, *QueryGetAllEraCheatStatusProcessDataRequest) (*QueryGetAllEraCheatStatusProcessDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllEraCheatStatusProcessData not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EpochLength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEpochLengthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EpochLength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EpochLength_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EpochLength(ctx, req.(*QueryGetEpochLengthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CurrentEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCurrentEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CurrentEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CurrentEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CurrentEpoch(ctx, req.(*QueryGetCurrentEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingNextEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPendingNextEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingNextEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PendingNextEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingNextEpoch(ctx, req.(*QueryGetPendingNextEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_HistoryEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetHistoryEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).HistoryEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_HistoryEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).HistoryEpoch(ctx, req.(*QueryGetHistoryEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllHistoryEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllHistoryEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllHistoryEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllHistoryEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllHistoryEpoch(ctx, req.(*QueryGetAllHistoryEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NodeWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNodeWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NodeWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_NodeWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NodeWorkload(ctx, req.(*QueryGetNodeWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllNodeWorkloadByEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllNodeWorkloadByEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllNodeWorkloadByEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllNodeWorkloadByEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllNodeWorkloadByEpoch(ctx, req.(*QueryGetAllNodeWorkloadByEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ManagerWRWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetManagerWRWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ManagerWRWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ManagerWRWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ManagerWRWorkload(ctx, req.(*QueryGetManagerWRWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllManagerWRWorkloadByEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllManagerWRWorkloadByEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllManagerWRWorkloadByEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllManagerWRWorkloadByEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllManagerWRWorkloadByEpoch(ctx, req.(*QueryGetAllManagerWRWorkloadByEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ManagerRPWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetManagerRPWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ManagerRPWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ManagerRPWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ManagerRPWorkload(ctx, req.(*QueryGetManagerRPWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllManagerRPWorkloadByEra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllManagerRPWorkloadByEraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllManagerRPWorkloadByEra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllManagerRPWorkloadByEra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllManagerRPWorkloadByEra(ctx, req.(*QueryGetAllManagerRPWorkloadByEraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ManagerCSWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetManagerCSWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ManagerCSWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ManagerCSWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ManagerCSWorkload(ctx, req.(*QueryGetManagerCSWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllManagerCSWorkloadByEra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllManagerCSWorkloadByEraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllManagerCSWorkloadByEra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllManagerCSWorkloadByEra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllManagerCSWorkloadByEra(ctx, req.(*QueryGetAllManagerCSWorkloadByEraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Workreport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetWorkreportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Workreport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Workreport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Workreport(ctx, req.(*QueryGetWorkreportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllWorkreportByEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllWorkreportByEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllWorkreportByEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllWorkreportByEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllWorkreportByEpoch(ctx, req.(*QueryGetAllWorkreportByEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_WorkreportProcessBatchSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetWorkreportProcessBatchSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WorkreportProcessBatchSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_WorkreportProcessBatchSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WorkreportProcessBatchSize(ctx, req.(*QueryGetWorkreportProcessBatchSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_HistoryEpochDataDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetHistoryEpochDataDepthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).HistoryEpochDataDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_HistoryEpochDataDepth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).HistoryEpochDataDepth(ctx, req.(*QueryGetHistoryEpochDataDepthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EpochProcessData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEpochProcessDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EpochProcessData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EpochProcessData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EpochProcessData(ctx, req.(*QueryGetEpochProcessDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllEpochProcessData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllEpochProcessDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllEpochProcessData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllEpochProcessData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllEpochProcessData(ctx, req.(*QueryGetAllEpochProcessDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Superior_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSuperiorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Superior(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Superior_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Superior(ctx, req.(*QueryGetSuperiorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EraLength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEraLengthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EraLength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EraLength_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EraLength(ctx, req.(*QueryGetEraLengthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CurrentEra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCurrentEraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CurrentEra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CurrentEra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CurrentEra(ctx, req.(*QueryGetCurrentEraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingNextEra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPendingNextEraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingNextEra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PendingNextEra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingNextEra(ctx, req.(*QueryGetPendingNextEraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_HistoryEra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetHistoryEraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).HistoryEra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_HistoryEra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).HistoryEra(ctx, req.(*QueryGetHistoryEraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllHistoryEra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllHistoryEraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllHistoryEra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllHistoryEra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllHistoryEra(ctx, req.(*QueryGetAllHistoryEraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReputationPointChangeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetReputationPointChangeDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReputationPointChangeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ReputationPointChangeData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReputationPointChangeData(ctx, req.(*QueryGetReputationPointChangeDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllReputationPointChangeDataByEra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllReputationPointChangeDataByEraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllReputationPointChangeDataByEra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllReputationPointChangeDataByEra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllReputationPointChangeDataByEra(ctx, req.(*QueryGetAllReputationPointChangeDataByEraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReputationDeltaPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetReputationDeltaPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReputationDeltaPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ReputationDeltaPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReputationDeltaPoint(ctx, req.(*QueryGetReputationDeltaPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllReputationDeltaPointByEra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllReputationDeltaPointByEraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllReputationDeltaPointByEra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllReputationDeltaPointByEra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllReputationDeltaPointByEra(ctx, req.(*QueryGetAllReputationDeltaPointByEraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EraProcessData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEraProcessDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EraProcessData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EraProcessData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EraProcessData(ctx, req.(*QueryGetEraProcessDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllEraProcessData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllEraProcessDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllEraProcessData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllEraProcessData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllEraProcessData(ctx, req.(*QueryGetAllEraProcessDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CheatStatusCRData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCheatStatusCRDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CheatStatusCRData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CheatStatusCRData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CheatStatusCRData(ctx, req.(*QueryGetCheatStatusCRDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllCheatStatusCRDataByEra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllCheatStatusCRDataByEraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllCheatStatusCRDataByEra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllCheatStatusCRDataByEra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllCheatStatusCRDataByEra(ctx, req.(*QueryGetAllCheatStatusCRDataByEraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EraCheatStatusProcessData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEraCheatStatusProcessDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EraCheatStatusProcessData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EraCheatStatusProcessData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EraCheatStatusProcessData(ctx, req.(*QueryGetEraCheatStatusProcessDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllEraCheatStatusProcessData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllEraCheatStatusProcessDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllEraCheatStatusProcessData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllEraCheatStatusProcessData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllEraCheatStatusProcessData(ctx, req.(*QueryGetAllEraCheatStatusProcessDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enreach.workload.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "EpochLength",
			Handler:    _Query_EpochLength_Handler,
		},
		{
			MethodName: "CurrentEpoch",
			Handler:    _Query_CurrentEpoch_Handler,
		},
		{
			MethodName: "PendingNextEpoch",
			Handler:    _Query_PendingNextEpoch_Handler,
		},
		{
			MethodName: "HistoryEpoch",
			Handler:    _Query_HistoryEpoch_Handler,
		},
		{
			MethodName: "AllHistoryEpoch",
			Handler:    _Query_AllHistoryEpoch_Handler,
		},
		{
			MethodName: "NodeWorkload",
			Handler:    _Query_NodeWorkload_Handler,
		},
		{
			MethodName: "AllNodeWorkloadByEpoch",
			Handler:    _Query_AllNodeWorkloadByEpoch_Handler,
		},
		{
			MethodName: "ManagerWRWorkload",
			Handler:    _Query_ManagerWRWorkload_Handler,
		},
		{
			MethodName: "AllManagerWRWorkloadByEpoch",
			Handler:    _Query_AllManagerWRWorkloadByEpoch_Handler,
		},
		{
			MethodName: "ManagerRPWorkload",
			Handler:    _Query_ManagerRPWorkload_Handler,
		},
		{
			MethodName: "AllManagerRPWorkloadByEra",
			Handler:    _Query_AllManagerRPWorkloadByEra_Handler,
		},
		{
			MethodName: "ManagerCSWorkload",
			Handler:    _Query_ManagerCSWorkload_Handler,
		},
		{
			MethodName: "AllManagerCSWorkloadByEra",
			Handler:    _Query_AllManagerCSWorkloadByEra_Handler,
		},
		{
			MethodName: "Workreport",
			Handler:    _Query_Workreport_Handler,
		},
		{
			MethodName: "AllWorkreportByEpoch",
			Handler:    _Query_AllWorkreportByEpoch_Handler,
		},
		{
			MethodName: "WorkreportProcessBatchSize",
			Handler:    _Query_WorkreportProcessBatchSize_Handler,
		},
		{
			MethodName: "HistoryEpochDataDepth",
			Handler:    _Query_HistoryEpochDataDepth_Handler,
		},
		{
			MethodName: "EpochProcessData",
			Handler:    _Query_EpochProcessData_Handler,
		},
		{
			MethodName: "AllEpochProcessData",
			Handler:    _Query_AllEpochProcessData_Handler,
		},
		{
			MethodName: "Superior",
			Handler:    _Query_Superior_Handler,
		},
		{
			MethodName: "EraLength",
			Handler:    _Query_EraLength_Handler,
		},
		{
			MethodName: "CurrentEra",
			Handler:    _Query_CurrentEra_Handler,
		},
		{
			MethodName: "PendingNextEra",
			Handler:    _Query_PendingNextEra_Handler,
		},
		{
			MethodName: "HistoryEra",
			Handler:    _Query_HistoryEra_Handler,
		},
		{
			MethodName: "AllHistoryEra",
			Handler:    _Query_AllHistoryEra_Handler,
		},
		{
			MethodName: "ReputationPointChangeData",
			Handler:    _Query_ReputationPointChangeData_Handler,
		},
		{
			MethodName: "AllReputationPointChangeDataByEra",
			Handler:    _Query_AllReputationPointChangeDataByEra_Handler,
		},
		{
			MethodName: "ReputationDeltaPoint",
			Handler:    _Query_ReputationDeltaPoint_Handler,
		},
		{
			MethodName: "AllReputationDeltaPointByEra",
			Handler:    _Query_AllReputationDeltaPointByEra_Handler,
		},
		{
			MethodName: "EraProcessData",
			Handler:    _Query_EraProcessData_Handler,
		},
		{
			MethodName: "AllEraProcessData",
			Handler:    _Query_AllEraProcessData_Handler,
		},
		{
			MethodName: "CheatStatusCRData",
			Handler:    _Query_CheatStatusCRData_Handler,
		},
		{
			MethodName: "AllCheatStatusCRDataByEra",
			Handler:    _Query_AllCheatStatusCRDataByEra_Handler,
		},
		{
			MethodName: "EraCheatStatusProcessData",
			Handler:    _Query_EraCheatStatusProcessData_Handler,
		},
		{
			MethodName: "AllEraCheatStatusProcessData",
			Handler:    _Query_AllEraCheatStatusProcessData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enreach/workload/query.proto",
}
