swagger: '2.0'
info:
  title: HTTP API Console enreach.registry
  name: ''
  description: ''
paths:
  /enreach/registry/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /enreach/registry/region/{code}:
    get:
      operationId: Query_Region
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Region:
                type: object
                properties:
                  code:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  creator:
                    type: string
                  createAt:
                    type: string
                    format: uint64
                  updator:
                    type: string
                  updateAt:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: code
          in: path
          required: true
          type: string
      tags:
        - Query
  /enreach/registry/regions:
    get:
      operationId: Query_RegionAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Region:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
                    creator:
                      type: string
                    createAt:
                      type: string
                      format: uint64
                    updator:
                      type: string
                    updateAt:
                      type: string
                      format: uint64
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /enreach/registry/superior:
    get:
      operationId: Query_Superior
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Superior:
                type: object
                properties:
                  account:
                    type: string
                  creator:
                    type: string
                  createAt:
                    type: string
                    format: uint64
                  updator:
                    type: string
                  updateAt:
                    type: string
                    format: uint64
                  signer:
                    type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  QueryAllRegionResponse:
    type: object
    properties:
      Region:
        type: array
        items:
          type: object
          properties:
            code:
              type: string
            name:
              type: string
            description:
              type: string
            creator:
              type: string
            createAt:
              type: string
              format: uint64
            updator:
              type: string
            updateAt:
              type: string
              format: uint64
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryGetRegionResponse:
    type: object
    properties:
      Region:
        type: object
        properties:
          code:
            type: string
          name:
            type: string
          description:
            type: string
          creator:
            type: string
          createAt:
            type: string
            format: uint64
          updator:
            type: string
          updateAt:
            type: string
            format: uint64
  QueryGetSuperiorResponse:
    type: object
    properties:
      Superior:
        type: object
        properties:
          account:
            type: string
          creator:
            type: string
          createAt:
            type: string
            format: uint64
          updator:
            type: string
          updateAt:
            type: string
            format: uint64
          signer:
            type: string
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  registry.Params:
    type: object
  registry.Region:
    type: object
    properties:
      code:
        type: string
      name:
        type: string
      description:
        type: string
      creator:
        type: string
      createAt:
        type: string
        format: uint64
      updator:
        type: string
      updateAt:
        type: string
        format: uint64
  registry.Superior:
    type: object
    properties:
      account:
        type: string
      creator:
        type: string
      createAt:
        type: string
        format: uint64
      updator:
        type: string
      updateAt:
        type: string
        format: uint64
      signer:
        type: string
  MsgCreateRegionResponse:
    type: object
  MsgCreateSuperiorResponse:
    type: object
  MsgDeleteRegionResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
  MsgUpdateRegionResponse:
    type: object
  MsgUpdateSuperiorResponse:
    type: object
  Params:
    type: object
